dbt_project:
  outputs:
    dev:
      dataset: dev_stay_informed
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /dbt/stayinformed.json
      location: US
      method: service-account
      priority: interactive
      project: stay-informed-429009
      threads: 1
      type: bigquery
  target: dev
